import type { Sense, ChoiceItem, ExplainItem, ActivityKind, Skill } from './types.ts';

/**
 * FIXTURE CONTENT. Original teaching text written for this prototype. Not from a licensed dictionary,
 * not editor-reviewed, Hindi text is an unreviewed draft. UI must label it as such (provenance.status).
 */
const PROV = { source: 'Wordwild original fixture', licence: 'Project-owned (unreleased)', status: 'fixture-unreviewed', updated: '2026-09-25' } as const;

type Opt = [text: string, why?: string];
function mc(id: string, kind: Exclude<ActivityKind, 'explain-back'>, skill: Skill, prompt: string, opts: Opt[], correct: number,
  explanation: string, hint: string, spoken?: string): ChoiceItem {
  const ids = ['a', 'b', 'c', 'd'];
  return {
    id, kind, skill, prompt, spoken, correctId: ids[correct], explanation, hint,
    options: opts.map(([text, why], i) => ({ id: ids[i], text, why })),
  };
}
const ex = (id: string, prompt: string, concepts: [string, string[]][], modelAnswer: string, hint: string): ExplainItem =>
  ({ id, kind: 'explain-back', skill: 'usage', prompt, concepts: concepts.map(([name, terms]) => ({ name, terms })), modelAnswer, hint });

const base = { lang: 'en', contentVersion: 1, provenance: PROV, antonyms: [] as string[] } as const;

export const SENSES: Sense[] = [
  {
    ...base, senseId: 'euphemism.n.1', lemma: 'euphemism', pos: 'noun', difficulty: 4,
    definition: 'A mild or indirect expression used instead of wording that might sound harsh, embarrassing or upsetting.',
    simple: 'A gentler way of saying something hard.',
    pronunciation: { text: 'YOO-fuh-miz-um', syllables: ['eu', 'phe', 'mism'], audioUrl: null },
    explanations: { hi: 'जब कोई कठोर या शर्मिंदा करने वाली बात को नरम शब्दों में कहा जाए, तो उस नरम कथन को euphemism कहते हैं।' },
    examples: [
      { text: '"Let go" is a euphemism for "fired".', context: 'work' },
      { text: 'She said her grandfather had "passed away", a gentle euphemism for died.', context: 'family' },
      { text: 'The notice used the euphemism "between jobs" instead of "unemployed".', context: 'public notice' },
    ],
    collocations: ['a euphemism for', 'gentle euphemism', 'polite euphemism'],
    relatedForms: ['euphemistic (adj)', 'euphemistically (adv)'],
    grammar: ['a euphemism for + noun/phrase'],
    nearSynonyms: [{ lemma: 'understatement', distinction: 'An understatement makes something sound smaller than it is; a euphemism replaces harsh wording.' }],
    register: 'neutral',
    suitableSituations: ['Talking about death, job loss or illness with care for feelings.'],
    unsuitableUses: ['Not every polite word is a euphemism; "please" softens nothing hidden.', 'Can hide important facts, for example in official reports.'],
    prerequisites: ['polite.adj.1', 'blunt.adj.1'], related: ['tactful.adj.1', 'indirect.adj.1', 'understatement.n.1'],
    practice: [
      mc('eu-1', 'meaning-bridge', 'meaning', 'The company "let him go". What does the softer phrase really mean?',
        [['He lost his job.'], ['He walked out of the building.', 'Literal reading. Here "let go" is the soft phrase.'], ['He got a promotion.', 'Nothing in the phrase suggests a promotion.']], 0,
        '"Let go" is a softer way to say the company ended his job.', 'Think: what happens when a company no longer wants a worker?'),
      mc('eu-2', 'conversation-choice', 'usage', 'Your friend\'s pet has died and they are very sad. Which sentence is the most gentle?',
        [['"Your dog is dead."', 'True, but blunt for this moment.'], ['"I\'m so sorry your dog passed away."'], ['"Your dog was a bit old anyway."', 'Unkind. It is not gentle, and not a euphemism.']], 1,
        '"Passed away" is a common euphemism that speaks gently about death.', 'Choose the words you would say to someone who is grieving.'),
      mc('eu-3', 'word-connections', 'reading', 'Which phrase softens an unpleasant fact instead of stating it?',
        [['"We are reducing headcount."'], ['"We have 40 workers."', 'A plain fact, not softened.'], ['"Our office is on the third floor."', 'Nothing unpleasant is being softened.']], 0,
        '"Reducing headcount" hides that real people lose their jobs. A euphemism can obscure facts.', 'Which phrase hides the real event?'),
      ex('eu-4', 'In your own words, explain what a euphemism is. Give an example if you can.',
        [['softer / gentler', ['soft', 'gentle', 'mild', 'kind', 'polite', 'less harsh', 'nice']], ['replaces something harsh', ['instead', 'rather than', 'harsh', 'upsetting', 'unpleasant', 'blunt', 'hard', 'embarrass']]],
        'A euphemism is a gentle way of saying something that would sound harsh or upsetting, like "passed away" for "died".', 'What do you say instead of a harsh word?'),
      mc('eu-5', 'memory-encounter', 'usage', 'A landlord\'s letter says the tenants "may need to relocate". What is going on?',
        [['The letter uses a euphemism for being told to leave.'], ['The tenants are moving for fun.', 'The wording is soft, but the situation is not a holiday.'], ['The tenants are buying the building.', 'Nothing supports that.']], 0,
        'Softer wording can hide that people are being made to leave. Noticing that is what the word helps with.', 'Is the wording hiding something unpleasant?'),
    ],
  },
  {
    ...base, senseId: 'tactful.adj.1', lemma: 'tactful', pos: 'adjective', difficulty: 3,
    definition: 'Careful not to upset or offend people when speaking or acting.',
    simple: 'Kind and careful with your words.',
    pronunciation: { text: 'TAKT-ful', syllables: ['tact', 'ful'], audioUrl: null },
    explanations: { hi: 'जो दूसरों को ठेस न पहुँचे, इस तरह सोच-समझकर बोले या करे, उसे tactful कहते हैं।' },
    examples: [
      { text: 'It was tactful of him to say nothing about her mistake in front of everyone.', context: 'workplace' },
      { text: 'A tactful teacher praises effort before pointing out errors.', context: 'school' },
      { text: 'She gave a tactful answer when asked if she liked the gift.', context: 'family' },
    ],
    collocations: ['tactful reply', 'tactful way', 'be tactful about'],
    relatedForms: ['tact (n)', 'tactfully (adv)', 'tactless (adj, opposite)'],
    grammar: ['It was tactful of + person + to + verb'],
    nearSynonyms: [{ lemma: 'polite', distinction: 'Polite follows good manners; tactful protects feelings in a delicate moment, even when the truth is hard.' }],
    antonyms: ['tactless'],
    register: 'neutral', suitableSituations: ['Giving feedback, refusing an invitation, talking about sensitive topics.'],
    unsuitableUses: ['Tactful does not mean dishonest.'],
    prerequisites: ['polite.adj.1'], related: ['euphemism.n.1', 'indirect.adj.1'],
    practice: [
      mc('ta-1', 'conversation-choice', 'usage', 'A colleague\'s presentation went badly. Which reply is the most tactful?',
        [['"That was terrible."', 'Blunt. It hurts and gives no help.'], ['"The ending was strong. Next time, let\'s tighten the middle."'], ['"I did not watch it."', 'Avoids feelings but is not honest or helpful.']], 1,
        'The tactful reply keeps honesty but protects feelings.', 'Which reply is honest and kind?'),
      mc('ta-2', 'meaning-bridge', 'meaning', 'Someone who is tactful is best described as…',
        [['Careful not to upset people.'], ['Always loud and fast.', 'Not related to being careful with feelings.'], ['Afraid to speak.', 'Tactful people do speak; they choose words with care.']], 0,
        'Tact is care about how your words affect others.', 'Think of choosing words with care.'),
      mc('ta-3', 'word-connections', 'meaning', 'How is "tactful" different from "polite"?',
        [['Polite is about manners; tactful is about protecting feelings in a delicate moment.'], ['They mean exactly the same.', 'They overlap but are not identical.'], ['Tactful means rude.', 'The opposite: tactless means insensitive.']], 0,
        'You can be polite (say "please") yet tactless (mention a sore subject).', 'One is about manners, one is about feelings.'),
    ],
  },
  {
    ...base, senseId: 'indirect.adj.1', lemma: 'indirect', pos: 'adjective', difficulty: 2,
    definition: 'Not stating something openly or straightforwardly.',
    simple: 'Not saying it straight.',
    pronunciation: { text: 'in-duh-REKT', syllables: ['in', 'di', 'rect'], audioUrl: null },
    explanations: { hi: 'जब बात सीधे न कहकर घुमा-फिराकर कही जाए, तो वह indirect है।' },
    examples: [
      { text: 'He gave an indirect answer instead of saying yes or no.', context: 'meeting' },
      { text: '"It is a bit cold in here" was her indirect way of asking him to close the window.', context: 'home' },
      { text: 'The manager was indirect about the problem and only hinted at it.', context: 'workplace' },
    ],
    collocations: ['indirect answer', 'indirect way', 'indirect hint'],
    relatedForms: ['indirectly (adv)'], grammar: ['an indirect way of + -ing'],
    nearSynonyms: [{ lemma: 'tactful', distinction: 'Indirect is about how plainly you speak; tactful is about care for feelings. An indirect message can be tactful or just unclear.' }],
    antonyms: ['direct', 'blunt'], register: 'neutral',
    suitableSituations: ['Hinting, when a direct request feels awkward.'], unsuitableUses: ['Emergencies or safety information should be direct.'],
    prerequisites: [], related: ['euphemism.n.1', 'blunt.adj.1'],
    practice: [
      mc('in-1', 'meaning-bridge', 'meaning', '"It is a bit cold in here." The speaker wants the window closed. This is…',
        [['An indirect request.'], ['A direct order.', 'A direct order would say "Close the window."'], ['A weather report only.', 'The context shows a request.']], 0,
        'The request is hinted, not stated.', 'Did they ask openly?'),
      mc('in-2', 'listen-and-find', 'listening', 'Listen. Which person is being indirect?',
        [['The one who says "Maybe we could look at other options."'], ['The one who says "No, I will not do it."', 'That is direct.'], ['The one who says "Yes, tomorrow at ten."', 'That is direct.']], 0,
        'Suggesting "other options" hints at a no without saying it.', 'Which one does not say the answer plainly?', 'Maybe we could look at other options.'),
      mc('in-3', 'conversation-choice', 'usage', 'A fire alarm rings. Who should speak in the clearest way?',
        [['"Leave now, use the stairs."', undefined], ['"It might be a good time to think about walking."', 'Too indirect for an emergency.'], ['"Some people prefer stairs."', 'Unclear and indirect.']], 0,
        'Emergencies need direct wording, so indirect is not always better.', 'Safety needs clear words.'),
    ],
  },
  {
    ...base, senseId: 'understatement.n.1', lemma: 'understatement', pos: 'noun', difficulty: 4,
    definition: 'A statement that makes something seem smaller, less important or less serious than it really is.',
    simple: 'Saying something big in a small way.',
    pronunciation: { text: 'UN-der-state-ment', syllables: ['un', 'der', 'state', 'ment'], audioUrl: null },
    explanations: { hi: 'किसी बड़ी बात को छोटा बताकर कहना understatement है।' },
    examples: [
      { text: '"It\'s a bit wet" was an understatement: the street was flooded.', context: 'weather' },
      { text: 'Calling the marathon "a short jog" is a joking understatement.', context: 'sport' },
      { text: 'The doctor\'s "a little discomfort" turned out to be an understatement.', context: 'health' },
    ],
    collocations: ['a huge understatement', 'to say the least is an understatement', 'typical British understatement'],
    relatedForms: ['understate (v)', 'understated (adj)'], grammar: ['That is an understatement.'],
    nearSynonyms: [{ lemma: 'euphemism', distinction: 'A euphemism replaces harsh wording to soften it; an understatement plays down the size of something, often with humour.' }],
    antonyms: ['exaggeration'], register: 'neutral',
    suitableSituations: ['Humour or dry commentary about something big.'], unsuitableUses: ['Can mislead when accuracy matters, such as in safety reports.'],
    prerequisites: ['indirect.adj.1'], related: ['euphemism.n.1'],
    practice: [
      mc('un-1', 'meaning-bridge', 'meaning', 'After a huge storm, someone says "It was a bit windy." This is…',
        [['An understatement.'], ['An exaggeration.', 'The opposite: it makes the storm sound smaller, not bigger.'], ['A precise measurement.', 'It is not precise at all.']], 0,
        'Making a big event sound small is understatement.', 'Does the phrase make the event sound bigger or smaller?'),
      mc('un-2', 'word-connections', 'meaning', 'Which pair is "euphemism" and which is "understatement"?',
        [['"Passed away" (euphemism); "a bit warm" for 45 degrees (understatement).'], ['"Passed away" (understatement); "a bit warm" for 45 degrees (euphemism).', 'Swapped. "Passed away" gently replaces "died"; "a bit warm" plays down a big fact.'], ['Both are euphemisms.', 'Only the first replaces a harsh word.']], 0,
        'Euphemism softens harsh wording. Understatement shrinks the size of a fact.', 'One replaces words; one shrinks size.'),
      ex('un-3', 'Explain what an understatement is, and give an example.',
        [['makes it smaller', ['small', 'less', 'down', 'minimi', 'little', 'not as bad', 'smaller']], ['really big/serious', ['big', 'serious', 'huge', 'really', 'actually', 'worse', 'important']]],
        'An understatement makes something big sound small, like saying "a bit wet" about a flood.', 'Is the thing really big, but described as small?'),
    ],
  },
  {
    ...base, senseId: 'polite.adj.1', lemma: 'polite', pos: 'adjective', difficulty: 1,
    definition: 'Having or showing good manners and respect for others.',
    simple: 'Showing good manners.',
    pronunciation: { text: 'puh-LITE', syllables: ['po', 'lite'], audioUrl: null },
    explanations: { hi: 'अच्छे व्यवहार और सम्मान के साथ पेश आना polite है।' },
    examples: [
      { text: 'It is polite to say thank you.', context: 'everyday' },
      { text: 'The shop assistant was polite even when the customer was angry.', context: 'shop' },
      { text: 'He gave a polite nod and waited for his turn.', context: 'queue' },
    ],
    collocations: ['polite request', 'polite to + person', 'be polite'], relatedForms: ['politely (adv)', 'politeness (n)', 'impolite (adj)'],
    grammar: ['It is polite to + verb'], nearSynonyms: [{ lemma: 'respectful', distinction: 'Respectful is about attitude; polite is about manners in behaviour.' }],
    antonyms: ['rude'], register: 'neutral', suitableSituations: ['Almost anywhere'], unsuitableUses: ['Politeness alone does not tell hard truths gently.'],
    prerequisites: [], related: ['tactful.adj.1', 'blunt.adj.1'],
    practice: [
      mc('po-1', 'listen-and-find', 'listening', 'Listen. Who is being polite?',
        [['The one who says "Excuse me, could you help me, please?"'], ['The one who says "Move."', 'Rude, not polite.'], ['The one who says nothing and pushes past.', 'That is impolite.']], 0,
        '"Excuse me", "could you" and "please" are polite.', 'Listen for "please" or "excuse me".', 'Excuse me, could you help me, please?'),
      mc('po-2', 'meaning-bridge', 'meaning', 'Which is a polite way to ask for water?',
        [['"Could I have some water, please?"'], ['"Water. Now."', 'Rude.'], ['"I do not like water."', 'Not a request.']], 0,
        'Polite requests use "could", "please" and a kind tone.', 'Pick the one with good manners.'),
      mc('po-3', 'conversation-choice', 'usage', 'You bump into someone on the bus. What is polite?',
        [['"Sorry, are you okay?"'], ['Look away and say nothing.', 'Silence can seem rude.'], ['"Watch where you stand!"', 'Rude, and it blames them.']], 0,
        'Apologising and checking on them is polite.', 'What would a caring person say?'),
    ],
  },
  {
    ...base, senseId: 'blunt.adj.1', lemma: 'blunt', pos: 'adjective', difficulty: 2,
    definition: 'Speaking in an honest, direct way that may be rude or hurtful, with little care for feelings.',
    simple: 'Saying it straight, without softening.',
    pronunciation: { text: 'BLUNT', syllables: ['blunt'], audioUrl: null },
    explanations: { hi: 'बिना नरम किए, सीधे और कभी-कभी कड़वे ढंग से बोलना blunt है।' },
    examples: [
      { text: 'To be blunt, your report is too long.', context: 'workplace' },
      { text: 'She is blunt: she tells you exactly what she thinks.', context: 'friends' },
      { text: 'The doctor was blunt about the risks.', context: 'health' },
    ],
    collocations: ['to be blunt', 'blunt answer', 'brutally blunt'], relatedForms: ['bluntly (adv)', 'bluntness (n)'],
    grammar: ['To be blunt, + statement'], nearSynonyms: [{ lemma: 'direct', distinction: 'Direct is neutral and can be kind; blunt suggests little care for feelings.' }],
    antonyms: ['tactful', 'diplomatic'], register: 'informal',
    suitableSituations: ['When clear honesty matters more than comfort.'], unsuitableUses: ['Comforting someone who is grieving.'],
    prerequisites: [], related: ['tactful.adj.1', 'indirect.adj.1'],
    practice: [
      mc('bl-1', 'meaning-bridge', 'meaning', '"To be blunt, I do not like the plan." The speaker is…',
        [['Speaking plainly, without softening.'], ['Speaking very quietly.', 'Loudness is not the point.'], ['Being sharp like a knife.', 'Only figurative; it means plain and harsh.']], 0,
        'Blunt = plain and unsoftened.', 'Is the speaker softening the message?'),
      mc('bl-2', 'word-connections', 'reading', 'Which word is the opposite of "blunt" in speech?',
        [['tactful'], ['loud', 'Loudness is different.'], ['honest', 'A blunt person can also be honest.']], 0,
        'Tactful speakers soften; blunt speakers do not.', 'Which word means careful with feelings?'),
      mc('bl-3', 'conversation-choice', 'usage', 'A friend shares a poem they wrote. Which reply is blunt?',
        [['"It is boring."'], ['"I liked the last line. Could the start be shorter?"', 'Tactful, not blunt.'], ['"Thank you for sharing it."', 'Polite, not blunt.']], 0,
        '"It is boring" says the hard thing with no softening.', 'Which reply has no softening at all?'),
    ],
  },
  // --- Ambiguity fixture: one lemma, two unrelated senses ---
  {
    ...base, senseId: 'fire.v.1', lemma: 'fire', pos: 'verb', difficulty: 2,
    definition: 'To dismiss someone from a job.',
    simple: 'To tell a worker to leave the job.',
    pronunciation: { text: 'FY-er', syllables: ['fire'], audioUrl: null },
    explanations: { hi: 'किसी को नौकरी से निकाल देना।' },
    examples: [
      { text: 'The shop fired him for being late every day.', context: 'work' },
      { text: 'She was afraid the boss would fire her.', context: 'fear' },
      { text: 'They fired three workers last week.', context: 'news' },
    ],
    collocations: ['fire someone', 'get fired', 'fired from'], relatedForms: ['firing (n)'], grammar: ['fire + person', 'be fired from + job'],
    nearSynonyms: [{ lemma: 'let go', distinction: '"Let go" is the softer, euphemistic phrase.' }], antonyms: ['hire'],
    register: 'informal', suitableSituations: ['Plainly describing a dismissal.'], unsuitableUses: ['Can sound harsh in a formal or sensitive setting.'],
    prerequisites: [], related: ['euphemism.n.1'],
    practice: [
      mc('fi-1', 'meaning-bridge', 'meaning', '"The manager fired Sam." What happened?',
        [['Sam lost his job.'], ['Sam lit a fire.', 'That is a different sense of "fire".'], ['Sam got a raise.', 'Opposite.']], 0, 'To fire someone = to dismiss them from work.', 'Think about jobs.'),
      mc('fi-2', 'word-connections', 'reading', 'Which softer phrase means the same as "fired"?',
        [['let go'], ['hired', 'Opposite.'], ['promoted', 'Opposite.']], 0, '"Let go" is a euphemism for "fired".', 'A gentler way to say it.'),
      mc('fi-3', 'listen-and-find', 'listening', 'Listen. What happened to the worker?',
        [['He lost his job.'], ['He started a fire.', 'That is a different sense of "fire".'], ['He was promoted.', 'Opposite.']], 0, 'Fired = dismissed.', 'Which sense of "fire"?', 'They fired the worker on Friday.'),
    ],
  },
  {
    ...base, senseId: 'fire.n.1', lemma: 'fire', pos: 'noun', difficulty: 1,
    definition: 'The heat, light and flames produced when something burns.',
    simple: 'Flames and heat.',
    pronunciation: { text: 'FY-er', syllables: ['fire'], audioUrl: null },
    explanations: { hi: 'आग: जलने से निकलने वाली लपटें और गर्मी।' },
    examples: [
      { text: 'We sat around the fire to keep warm.', context: 'camping' },
      { text: 'A small fire started in the kitchen.', context: 'home' },
      { text: 'The fire spread quickly through the dry grass.', context: 'nature' },
    ],
    collocations: ['light a fire', 'on fire', 'put out a fire'], relatedForms: ['fiery (adj)'], grammar: ['a fire / fires (countable); fire (uncountable)'],
    nearSynonyms: [{ lemma: 'flame', distinction: 'A flame is one tongue of fire; fire is the whole burning.' }], antonyms: [],
    register: 'neutral', suitableSituations: ['Cooking, warmth, danger.'], unsuitableUses: ['"On fire" means actually burning; for a hard-working person say "on fire" only as a casual figure of speech.'],
    prerequisites: [], related: [],
    practice: [
      mc('fn-1', 'meaning-bridge', 'meaning', '"We lit a fire to cook dinner." What did they make?',
        [['Flames and heat.'], ['A job.', 'That is the verb sense of "fire".'], ['A meal plan.', 'Not related.']], 0, 'Fire = burning with flames.', 'Think of camping.'),
      mc('fn-2', 'listen-and-find', 'listening', 'Listen. What is happening?',
        [['Something is burning.'], ['Someone lost a job.', 'Different sense of "fire".'], ['Someone is sleeping.', 'Not related.']], 0, 'Flames are the fire sense here.', 'Listen for smoke or flames.', 'There is a fire in the kitchen!'),
      mc('fn-3', 'word-connections', 'reading', 'Which word goes with "fire"?',
        [['flames'], ['salary', 'Belongs with jobs.'], ['pillow', 'Not related.']], 0, 'Flames belong with fire.', 'What comes from a fire?'),
    ],
  },
];

export const SENSE_BY_ID: Record<string, Sense> = Object.fromEntries(SENSES.map(s => [s.senseId, s]));
